### ISSUE TITLE
matuc imgdsc returns a absolute path

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#33]
The matuc command 
`matuc imgdsc -d descriptionText C:\temp\k01\images\img_1.jpg`
returns
~~~
internal:
  ![descriptionText](C:\temp\k01\images\img_1.jpg)
~~~
but that should be
` ![descriptionText](images/img_1.jpg)`

**Comment by humenda** [comment]
This is expected behaviour, you are calling `matuc imgdsc` with an absolute path, so you end up with an absolute path. Try a relative path instead.

**Comment by jevo** [comment]
If I enter a relative path like `matuc imgdsc -d descriptionText image.jpg`

matuc returns
```
internal:
  ![descriptionText](image.jpg)
```

If I add a path like `images\images.jpg`.
The complete command is `MAGSBS.errors.ConfigurationError`
that causes a MAGSBS.errors.ConfigurationError,

```
The Traceback (most recent call last):
  File "matuc.py", line 609, in <module>
  File "matuc.py", line 291, in run
  File "matuc.py", line 447, in handle_imgdsc
  File "Z:\home\jDoe\uni\agsbs\MAGSBS_markdown-plugin\MAGSBS\factories.py",
 line 41, in __init__
  File "Z:\home\jDoe\uni\agsbs\MAGSBS_markdown-plugin\MAGSBS\config.py", li
ne 264, in get_conf_instance
MAGSBS.errors.ConfigurationError: in configuration images: specified path doesn'
t exist

```

**Comment by humenda** [comment]
The traceback shows that this is an unrelated issue, but let's discuss that as well :).
This error is caused, because you're executing this command from the wrong directory. I do admit that the error message is misleading (I could easily fix that), but the question is, whether it is a problem for the user to execute matuc imgdsc from the correct directory?
The command assumes, that the referenced, relative path actually exists. This is necessary, because the output strings get localized and this is impossible without a configuration. I could silently ignore these cases, where no configuration exists, with the risk of swallowing improper use of the programm. Alternatively, I could rework the configuration message.

**Comment by humenda** [comment]
This error does actually not exist: according to the command documentation:

usage: matuc imgdsc [-h] [-d DESC] [-o] [-t TITLE] [path]

The working directory must be a chapter of a book or of another kind of
material; the image name must be a path relative to the current working
directory.
